#!/bin/bash
# Get my public ip address, it's very usable in internal 
# network environment especially.
# zhe.chen<chenzhe07@gmail.com>

exec 2>&1

if [ $# -gt 0 ]; then
   echo "Usage: sys-pubip"
fi

curlcmd=$(which curl)
if [ ! -x $curlcmd ]; then
   echo "can not find curl command or with no permission"
   exit 1
fi

urls="ipinfo.io/ip ipecho.net/plain"

echo "Get public ip address:"
OUTPUT=0

timeoutcmd=$(which timeout)
for url in $urls; do
   OUTPUT=$($timeoutcmd 5 $curlcmd -s $url)
   echo $OUTPUT | grep -P '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' >/dev/null
   if [ $? -eq 0 ]; then
      echo $OUTPUT
      break
   else
      echo "curl $url error"
   fi
done
