#!/bin/bash
# prevent killing MySQL process by oom-killer
# https://www.percona.com/blog/wp-content/uploads/2014/04/Running-MySQL-on-CentOS-Linux.pdf
# zhe.chen<chenzhe07@gmail.com>

exec 2>&1

if [ $# -gt 0 ]; then
   echo "Usage: sys-mysql-adj"
fi

pidofcmd=$(which pidof)
if [ ! -x $pidofcmd ]; then
   echo "can not find pidof command or has no permission"
   exit 1
fi

mysqlpids=$($pidofcmd mysqld)

if [ -z "$mysqlpids" ]; then
   echo "no MySQL process";
   exit 0;
fi

echo "oom_adj mysqld process"
for mysql_pid in $mysqlpids; do
   if [ -n $mysql_pid ]; then
      if [ "`cat /proc/$mysql_pid/oom_adj`" -ne -17 ]; then
          echo -17 > /proc/$mysql_pid/oom_adj
          echo "pid $mysql_pid oom_adj = -17"
      fi
   fi
done

# Documentation
: <<'DOCUMENTATION'
=pod

=head1 NAME

sys-mysql-adj - prevent system killing local host MySQL process by oom-killer

=head1 SYNOPSIS

  Usage: sys-mysql-adj

  eg:
     $ ./sys-mysql-adj
     oom_adj mysqld process
     pid 31265 oom_adj = -17
     pid 25653 oom_adj = -17
     pid 20247 oom_adj = -17

     $ ./sys-mysql-adj
     no MySQL process

  note: Can be used without args.

=head1 AUTHOR

chenzhe07@gmail.com

=head1 VERSION

sys-mysql-adj 0.1.0

=cut

DOCUMENTATION
