#!/bin/bash
# echo message to STDERR
# zhe.chen<chenzhe07@gmail.com>

#exec 2>&1

if [ $# -eq 0 ]; then
   echo "Usage: sys-echo-stderr msg1 msg2 ..."
fi

echocmd=$(which echo)
if [ ! -x $echocmd ]; then
   echo "can not find echo command or has no permission"
   exit 1
fi

$echocmd $* 1>&2

exit $?

# Documentation
: <<'DOCUMENTATION'
=pod

=head1 NAME

sys-echo-stderr - echo message to STDERR.

=head1 SYNOPSIS

  Usage: sys-echo-stderr [message]

  eg:
    $ ./sys-echo-stderr hello world >1.txt 
    hello world

=head1 AUTHOR

chenzhe07@gmail.com

=head1 VERSION

sys-echo-stderr 0.1.0

=cut

DOCUMENTATION
